### ISSUE TITLE
devnet-start, failed to start transient timer uint

### ISSUE THREAD

**Issue by waozixyz** [thomashoneyman/real-world-pact#11]
Hi, I'm getting a strange error when i try to run devnet-start and I am not sure how to move forward from this.

```
ERRO[0000] Failed to start transient timer unit: Unit a6de4ba116b474a471a71a96347ccbb8dffaa79c1010b26cce89493378318fb6.timer was already loaded or has a fragment file. 
```

I'm running nix-os, with podman + podman-compose instead of docker.

**Comment by waozixyz** [comment]
nvm, think i solved the issue by running devnet directly with docker

**Comment by thomashoneyman** [comment]
Great, glad that worked — I'm not sure about any odd interactions between devnet and podman, but it certainly should work with docker.
