### ISSUE TITLE
Pact in 20 minutes doesn't offer a clear cut, fast way to install pact

### ISSUE THREAD

**Issue by trendzetter** [thomashoneyman/real-world-pact#8]
Many people are massively overwhelmed and confused by all the options to install from source. A quickstart should just skip that and point strait to the binary distributions imo. At some point the binaries are mentioned, it says "see below", but I can't even find the actual link.
Building from source should be considered advanced usage. Not many people are used to build their development tools from source, and its especially intimidating to people new to the world of lisp and haskell (large majority of the audience).

**Comment by thomashoneyman** [comment]
In the article I link to the installation instructions in the Pact repo. Is there a better place to link? I don’t offer any installation instructions beyond whatever is official (or via Nix, which I use in this repo).

**Comment by trendzetter** [comment]
you are right, it was late at night when I wrote my initial comment. I missed that I was redirected at the main pact readme. I do think the pact readme is confusing for newcomers. So the only thing that could be of any value for your "pact in 20 minutes" guide is maybe make sure users don't get stuck in the options offered by kadena's readme -i will try if I can get a pr accepted there as well-
